services:
  postgres_db:
    image: postgres:15
    container_name: greenfield_sql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=fab_metadata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - greenfield_net

  influx_db:
    image: influxdb:2.7
    container_name: greenfield_db
    restart: always
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_ORG=greenfield_inc
      - DOCKER_INFLUXDB_INIT_BUCKET=wafer_telemetry
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-admin-token-123
    networks:
      - greenfield_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: greenfield_api
    ports:
      - "8000:8000"
    depends_on:
      influx_db:  # MATCH the service name above
        condition: service_healthy
      postgres_db: # Also wait for Postgres
        condition: service_started
    environment:
      - INFLUXDB_URL=http://influx_db:8086 # MATCH the service name
      - INFLUXDB_TOKEN=my-super-secret-admin-token-123
      - INFLUXDB_ORG=greenfield_inc
      - INFLUXDB_BUCKET=wafer_telemetry
      # Add the SQL connection string for SQLAlchemy
      - DATABASE_URL=postgresql://admin:password123@postgres_db:5432/fab_metadata
    networks:
      - greenfield_net

  sim:
    build: ./sim
    container_name: greenfield_sim
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000/api/v1/telemetry
    networks:
      - greenfield_net

networks:
  greenfield_net:
    driver: bridge

volumes:
  postgres_data:
  influxdb_data:
